### PR TITLE
solved MDB_BAD_VALSIZE

### PR DESCRIPTION
**Pull request by snlpatel001213**
I was getting the error "mdb_put: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size". This error was reported in one of the word/vector out millions but due to this error entire write operation was failing. Many users are facing the same user. I have tested my fix and it is working, this will help other users who are facing the same error. @DomHudson Please merge this.

### CODE REVIEW

**Comment by snlpatel001213** [comment]
@DomHudson Please merge this.

**Comment by DomHudson** [comment]
Hi thanks for your contribution. I believe this is because the key (the word) is longer than the max allowed size. I will put in a constraint on this. Are you able to provide the word vector pair that caused the exception?

**Comment by DomHudson** [comment]
I'm not going to merge this as is - I think we should explicitly catch the correct exception and log with warnings rather than printing. Assuming it is the length of the word - I will try to get something in for that soon.

**Comment by DomHudson** [comment]
Hi, I have put in a direct check for the maximum key size in this PR. https://github.com/ThoughtRiver/lmdb-embeddings/pull/5 This should fix your issue. Please let me know if it does not.

**Pull request closed without merging**
